### ISSUE TITLE
CSS Flexbox Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#12]
Implement flexbox that allows elements to lay themselves out automatically.
- [ ] Apply `flex` to the `display` property
- [ ] Must have more than two children on element using flexbox
- [ ] Must use minimum of three flexbox related attributes
