### ISSUE TITLE
CSS Grid Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#13]
Implement grid for the layouts
- [ ] Apply `grid` to `display` property
- [ ] Must have more than two children within element using the grid
- [ ] Must use minimum of three grid related attributes
