### ISSUE TITLE
CSS Regular Selectors Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#16]
Implement various types of selectors to select HTML elements to style.
- [x] Class Selector (`.class`)
- [x] ID Selector (`#id`)
- [x] Universal Selector (`*`)
- [x] Event selector (`element`)
- [x] Attribute selector (e.g. `[attribute=foo]`)
- [x] Psuedo-class Selector (e.g. `p:hover`)
- [x] Selector List (`element, element`)
