### ISSUE TITLE
CSS Combinators Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#17]
Specify selections based on element positioning in the DOM tree 
- [ ] Decendant Combinator (`element element`)
- [ ] Child Combinator (`element > element`)
- [ ] General Sibling Combinator (`element ~ element`)
- [ ] Adjacent Sibling Combinator (`element + element`)
- [ ] Combining Two Selectors (`element.class`)
