### ISSUE TITLE
CSS Color Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#3]
Implement Colors to HTML elements in CSS Stylesheet.
- [x] rgb(r, g, b) or rgba(r, g, b, a)     /* red, green, blue, alpha values */
- [x] #FFF or #FFFFFF                    /* hex codes */
- [x] hsl(h, s, l) or hsla(h, s, l, a)       /* hue, saturation, lightness, alpha values */
- [x] Color Name
