### ISSUE TITLE
CSS Box Model Checklist Item

### ISSUE THREAD

**Issue by lyurrutia** [lyurrutia/fa21-cse110-lab3#6]
Configure containers that hold HTML content in CSS Stylesheet.

## Margin
Spacing between html elements
- [x] Long (`margin-top, margin-bottom, margin-left, margin-right`)
- [x] Short (`margin: <top> <right> <bottom> <left>`)
- [x] Auto margins: `margin: auto`
## Padding
Spacing within html elements
- [x] Long (`padding-top, padding-bottom, padding-left, padding-right`)
- [x] Short (`padding: <top> <right> <bottom> <left>`)
## Borders
borders around html elements (try before using margin/padding)
- [x] `border-style`
- [x] `border-color`
- [x] `border-width`
- [x] `border-radius`
